[en-us]
resume-title = "Resume of {}"
resume-description = "Resume of {}"
tonow = "Now"
supervisor = "Supervisor"

[zh-cn]
resume-title = "{}的简历"
resume-description = "{}的个人简历"
tonow = "至今"
supervisor = "导师"
