name: Build examples

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.example }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - example_en-us.typ
          - example_zh-cn.typ

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install necessary fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-linuxlibertine fonts-noto-cjk fonts-noto-cjk-extra \
            fonts-noto-core

      - name: Install Typst
        uses: typst-community/setup-typst@v5
        with:
          typst-version: 0.14.2

      - name: Compile the example
        run: typst compile "${{ matrix.example }}"
